name: "Create Branch QA"

on:
  workflow_dispatch:

jobs:
  create-branch-qa:
    name: "Job Create Branch QA"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Branch Actual name
        run: git rev-parse --abbrev-ref HEAD
        
      - name: Fetch All
        run: git fetch --all

      - name: Branch Actual name
        run: git rev-parse --abbrev-ref HEAD

      - name: Create QA branch
        run: git checkout -b QA
        
      - name: Branch Actual name
        run: git rev-parse --abbrev-ref HEAD
        
      - name: Merge first branch
        run: git merge origin/branch-main --no-edit --allow-unrelated-histories
        
      - name: Branch Actual name
        run: git rev-parse --abbrev-ref HEAD
        
      - name: Merge second branch
        run: git merge origin/branch-test --no-edit --allow-unrelated-histories
        
      - name: Branch Actual name
        run: git rev-parse --abbrev-ref HEAD
        
      - name: Pull QA Branch
        run: git pull origin QA
        
      - name: Branch Actual name
        run: git rev-parse --abbrev-ref HEAD
