name: "Create Branch QA"

on:
  workflow_dispatch:
    inputs:
      branch_intermediaria:
        type: string
        description: "Informe o nome da branch intermediaria"
        default: "qa"
        required: true
      branches:
        type: string
        description: "Informe as branchs separadas por virgula Ex: branch1,branch2,branch3"
        required: true

jobs:
  create-branch-qa:
    name: "Job Create Branch QA"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: 'master'
          token: "${{ secrets.GITHUBWRITETOKEN }}"
      - name: Executa comandos git
        env:
          brnchs: ${{ github.event.inputs.branches }}
        run: |
            git config --global user.email "${{ secrets.GITUSERNAME }}"
            git config --global user.name "${{ secrets.GITUSEREMAIL }}"
            git config --global pull.ff only
            git fetch
            git pull origin master
            IFS=';' read -ra ADDR <<< "$brnchs"
            for i in "${ADDR[@]}"; do
              git checkout $i
              git pull origin $i
            done
            git checkout -b ${{ github.event.inputs.branch_intermediaria }}
            IFS=';' read -ra ADDR <<< "$brnchs"
            for i in "${ADDR[@]}"; do
              git merge $i --no-edit --allow-unrelated-histories
            done
            git push origin ${{ github.event.inputs.branch_intermediaria }}
