name: "Create Branch QA"

on:
  workflow_dispatch:

jobs:
  create-branch-qa:
    name: "Job Create Branch QA"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: 'master'
          token: "${{ secrets.GITHUBWRITETOKEN }}"
      - run: |
            git config --global user.email "${{ secrets.GITUSERNAME }}"
            git config --global user.name "${{ secrets.GITUSEREMAIL }}"
            git config --global pull.ff only
            git fetch
            git pull origin master
            git checkout branch-main
            git pull origin branch-main
            git checkout branch-test
            git pull origin branch-test
            git checkout -b QA
            git merge branch-main --no-edit --allow-unrelated-histories
            git merge branch-test --no-edit --allow-unrelated-histories
            git push origin QA
