name: "Create Branch QA"

on:
  workflow_dispatch:
    inputs:
      branch_intermediary:
        type: string
        description: "Informe o nome da branch intermediária"
        default: "qa"
        required: true
      branches_to_combine:
        type: string
        description: "Informe as branchs separadas por ';' Ex: branch1;branch2;branch3"
        required: true

jobs:
  create-branch-qa:
    name: "Job Create Branch QA"
    runs-on: ubuntu-latest
    env:
        branches_to_combine: ${{ github.event.inputs.branches_to_combine }}
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: 'master'
          token: "${{ secrets.GITHUBWRITETOKEN }}"
      - name: Config git
        run: |
            git config --global user.email "${{ secrets.GITUSERNAME }}"
            git config --global user.name "${{ secrets.GITUSEREMAIL }}"
            git config --global pull.ff only

      - name: Fetch all and pull master
        run: |
            git fetch
            git pull origin master

      - name: Checkout "${{ branches_to_combine }}" branches
        run: |
            IFS=';' read -ra ADDR <<< "$branches_to_combine"
            for i in "${ADDR[@]}"; do
              git checkout $i
              git pull origin $i
            done

      - name: Creating "${{ github.event.inputs.branch_intermediary }}" branch
        run: |
            git checkout -b ${{ github.event.inputs.branch_intermediary }}

      - name: Merge "${{ branches_to_combine }}" into "${{ github.event.inputs.branch_intermediary }}" branch
        run: |
            IFS=';' read -ra ADDR <<< "$branches_to_combine"
            for i in "${ADDR[@]}"; do
              git merge $i --no-edit --allow-unrelated-histories
            done

      - name: Push "${{ github.event.inputs.branch_intermediary }}"
        run: |
            git push origin ${{ github.event.inputs.branch_intermediary }}