name: "Create Branch QA"

on:
  workflow_dispatch:

jobs:
  create-branch-qa:
    name: "Job Create Branch QA"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          token: "${{ secrets.GITHUBWRITETOKEN }}"

      - name: Config git
        run: |
            git config --global user.name "${{ secrets.GITUSERNAME }}"
            git config --global user.email "${{ secrets.GITUSEREMAIL }}"

      - name: Branch Actual name
        run: |
            git rev-parse --abbrev-ref HEAD
            git branch -v -a
        
      - name: Fetch All
        run: git fetch --all

      - name: Branch Actual name
        run: |
            git rev-parse --abbrev-ref HEAD
            git branch -v -a
        
      - name: Prepare first branch
        run: |
            git switch orgin/branch-main
        
      - name: Branch Actual name
        run: |
            git rev-parse --abbrev-ref HEAD
            git branch -v -a

      - name: Prepare second branch
        run: |
            git switch orgin/branch-test
        
      - name: Branch Actual name
        run: |
            git rev-parse --abbrev-ref HEAD
            git branch -v -a

      - name: Back to master base
        run: git checkout master
        
      - name: Branch Actual name
        run: |
            git rev-parse --abbrev-ref HEAD
            git branch -v -a

      - name: Create QA branch
        run: git checkout -b QA
        
      - name: Branch Actual name
        run: |
            git rev-parse --abbrev-ref HEAD
            git branch -v -a

      - name: Merge first branch
        run: git merge origin/branch-main --no-edit --allow-unrelated-histories
        
      - name: Branch Actual name
        run: |
            git rev-parse --abbrev-ref HEAD
            git branch -v -a

      - name: Merge second branch
        run: git merge origin/branch-test --no-edit --allow-unrelated-histories
        
      - name: Branch Actual name
        run: |
            git rev-parse --abbrev-ref HEAD
            git branch -v -a
        
      - name: Pull QA Branch
        run: git push origin QA
        
      - name: Branch Actual name
        run: |
            git rev-parse --abbrev-ref HEAD
            git branch -v -a
