name: "Postman Confluence"

on:
  push:
    branches:
      - master
    paths:
      - 'docs/environment.json'
      - 'docs/postman.json'
  workflow_dispatch:

jobs:
  postman-confluence:
    name: "Postman Confluence"
    runs-on: "ubuntu-latest"
    env:
      COMMENT_MSG: ${{ github.event.head_commit.message }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
    
      - name: Checkout master
        uses: actions/checkout@v3
        with:
          ref: master
          token: ${{ secrets.GITHUBWRITETOKEN }}

      - name: Curiosidade
        run: |
            echo -e "-------------------------"
            ls -lorth /home/runner/work/
            echo -e "-------------------------"
            ls -lorth /home/runner/work/poc-deps-up-to-date/
            echo -e "-------------------------"
            ls -lorth /home/runner/work/poc-deps-up-to-date/poc-deps-up-to-date/
            
      - name: Attaching Postman files in Confluence
        run: |
            for entry in docs/postman/*.json
            do
              CURRENT_FILE=$(readlink -f $entry)
              echo -e "Full path: $CURRENT_FILE"
            done
