name: "Postman Confluence"

on:
  push:
    branches:
      - master
    paths:
      - 'docs/environment.json'
      - 'docs/postman.json'
  workflow_dispatch:

jobs:
  postman-confluence:
    name: "Postman Confluence"
    runs-on: "ubuntu-latest"
    steps:
      - name: Print
        run: echo "Teste"
